import type { ArtistMoment, ArtistProfile } from "@/types";

export const MOCK_PROFILE: ArtistProfile = {
  id: "artist-1",
  name: "Soyeon Kim",
  bio: "Painter exploring structure and repetition",
  ritualPosts: 42,
  streak: 11,
  exhibitions: 3,
  activityLogs: 67,
};

const now = Date.now();
const day = 86400000;

export const MOCK_MOMENTS: ArtistMoment[] = [
  {
    id: "m1",
    artistId: "a2",
    artistName: "Minji Park",
    imageUri: "https://picsum.photos/400/400?random=1",
    note: "Ruined the surface again, but maybe that's the direction.",
    state: "stuck",
    medium: "painting",
    createdAt: new Date(now - 2 * day).toISOString(),
  },
  {
    id: "m2",
    artistId: "a3",
    artistName: "Yuki Tanaka",
    imageUri: "https://picsum.photos/400/400?random=2",
    note: "Experimenting with charcoal on paper. The grain is different than I expected.",
    state: "experimenting",
    medium: "drawing",
    createdAt: new Date(now - 3 * day).toISOString(),
  },
  {
    id: "m3",
    artistId: "a4",
    artistName: "Alex Chen",
    imageUri: "https://picsum.photos/400/400?random=3",
    note: "Studio floor. Starting over.",
    state: "thinking",
    medium: "mixed media",
    createdAt: new Date(now - 4 * day).toISOString(),
  },
  {
    id: "m4",
    artistId: "a5",
    artistName: "Elena Vasquez",
    imageUri: "https://picsum.photos/400/400?random=4",
    note: "Third attempt at this composition. Still not right.",
    state: "stuck",
    medium: "painting",
    createdAt: new Date(now - 5 * day).toISOString(),
  },
  {
    id: "m5",
    artistId: "a6",
    artistName: "James Okonkwo",
    imageUri: "https://picsum.photos/400/400?random=5",
    note: "Clay drying. Waiting for the right moment to continue.",
    state: "working",
    medium: "sculpture",
    createdAt: new Date(now - 5 * day).toISOString(),
  },
  {
    id: "m6",
    artistId: "a7",
    artistName: "Sofia Lindberg",
    imageUri: "https://picsum.photos/400/400?random=6",
    note: "Light through the window at 4pm. Trying to catch it.",
    state: "experimenting",
    medium: "photography",
    createdAt: new Date(now - 6 * day).toISOString(),
  },
  {
    id: "m7",
    artistId: "a8",
    artistName: "Marco Rossi",
    imageUri: "https://picsum.photos/400/400?random=7",
    note: "Scrapped the whole thing. Sometimes that's the only way.",
    state: "thinking",
    medium: "painting",
    createdAt: new Date(now - 7 * day).toISOString(),
  },
  {
    id: "m8",
    artistId: "a9",
    artistName: "Nina Kowalski",
    imageUri: "https://picsum.photos/400/400?random=8",
    note: "Sketchbook page. Nothing finished, everything in progress.",
    state: "working",
    medium: "drawing",
    createdAt: new Date(now - 8 * day).toISOString(),
  },
  {
    id: "m9",
    artistId: "a10",
    artistName: "David Park",
    imageUri: "https://picsum.photos/400/400?random=9",
    note: "Installation day. The space changes everything.",
    state: "working",
    medium: "mixed media",
    createdAt: new Date(now - 9 * day).toISOString(),
  },
  {
    id: "m10",
    artistId: "a11",
    artistName: "Luna Nakamura",
    imageUri: "https://picsum.photos/400/400?random=10",
    note: "Wrote three pages. Deleted two. The one that stayed might be the start.",
    state: "experimenting",
    medium: "writing",
    createdAt: new Date(now - 10 * day).toISOString(),
  },
  {
    id: "m11",
    artistId: "a12",
    artistName: "Omar Hassan",
    imageUri: "https://picsum.photos/400/400?random=11",
    note: "Palette at the end of the day. Every color I tried today.",
    state: "working",
    medium: "painting",
    createdAt: new Date(now - 11 * day).toISOString(),
  },
  {
    id: "m12",
    artistId: "a13",
    artistName: "Freya Andersen",
    imageUri: "https://picsum.photos/400/400?random=12",
    note: "Staring at the wall. Sometimes the work happens before the work.",
    state: "thinking",
    medium: "mixed media",
    createdAt: new Date(now - 12 * day).toISOString(),
  },
  {
    id: "m13",
    artistId: "a14",
    artistName: "Ravi Singh",
    imageUri: "https://picsum.photos/400/400?random=13",
    note: "Failed cast. Will try again tomorrow with different ratio.",
    state: "stuck",
    medium: "sculpture",
    createdAt: new Date(now - 13 * day).toISOString(),
  },
  {
    id: "m14",
    artistId: "a15",
    artistName: "Claire Dubois",
    imageUri: "https://picsum.photos/400/400?random=14",
    note: "New paper. First mark. The blank page is always a little frightening.",
    state: "experimenting",
    medium: "drawing",
    createdAt: new Date(now - 14 * day).toISOString(),
  },
  {
    id: "m15",
    artistId: "a16",
    artistName: "Hassan Ibrahim",
    imageUri: "https://picsum.photos/400/400?random=15",
    note: "Documenting the process. The in-between matters.",
    state: "working",
    medium: "photography",
    createdAt: new Date(now - 15 * day).toISOString(),
  },
  {
    id: "m16",
    artistId: "a17",
    artistName: "Maya Johnson",
    imageUri: "https://picsum.photos/400/400?random=16",
    note: "Couldn't sleep. Came to the studio at 3am. Something is shifting.",
    state: "thinking",
    medium: "painting",
    createdAt: new Date(now - 16 * day).toISOString(),
  },
  {
    id: "m17",
    artistId: "a18",
    artistName: "Leo Zhang",
    imageUri: "https://picsum.photos/400/400?random=17",
    note: "Tore it up. Started again. The second version is never the same.",
    state: "experimenting",
    medium: "mixed media",
    createdAt: new Date(now - 17 * day).toISOString(),
  },
  {
    id: "m18",
    artistId: "a19",
    artistName: "Zara Williams",
    imageUri: "https://picsum.photos/400/400?random=18",
    note: "Words today. No images. Sometimes the ritual is just showing up.",
    state: "working",
    medium: "writing",
    createdAt: new Date(now - 18 * day).toISOString(),
  },
  {
    id: "m19",
    artistId: "a20",
    artistName: "Kai Müller",
    imageUri: "https://picsum.photos/400/400?random=19",
    note: "The piece that didn't make it to the show. Still means something.",
    state: "stuck",
    medium: "sculpture",
    createdAt: new Date(now - 19 * day).toISOString(),
  },
  {
    id: "m20",
    artistId: "a21",
    artistName: "Aria Patel",
    imageUri: "https://picsum.photos/400/400?random=20",
    note: "Small study. Not for anyone. Just to see what happens.",
    state: "working",
    medium: "painting",
    createdAt: new Date(now - 20 * day).toISOString(),
  },
];
