export type PortalGallerySeed = {
  galleryId: string;
  name: string;
  country: string;
  city: string;
  website?: string;
  bio?: string;
  sourcePortal: string;
  sourceUrl?: string;
  externalEmail?: string;
};

// Initial directory seeds from major-portal style discovery.
// This list is intentionally explicit and easy to extend per country/city.
export const PORTAL_GALLERY_SEEDS: PortalGallerySeed[] = [
  // Korea
  {
    galleryId: "__ext_dir_kukje_seoul",
    name: "Kukje Gallery",
    country: "한국",
    city: "Seoul",
    website: "https://www.kukjegallery.com",
    bio: "Leading contemporary gallery in Seoul.",
    sourcePortal: "Naver",
    sourceUrl: "https://www.kukjegallery.com",
  },
  {
    galleryId: "__ext_dir_hyundai_seoul",
    name: "Gallery Hyundai",
    country: "한국",
    city: "Seoul",
    website: "https://www.galleryhyundai.com",
    bio: "Historic Korean gallery with international program.",
    sourcePortal: "Naver",
    sourceUrl: "https://www.galleryhyundai.com",
  },
  {
    galleryId: "__ext_dir_johyun_busan",
    name: "Johyun Gallery",
    country: "한국",
    city: "Busan",
    website: "https://www.johyungallery.com",
    bio: "Major gallery in Busan for Korean and global artists.",
    sourcePortal: "Naver",
    sourceUrl: "https://www.johyungallery.com",
  },

  // Japan
  {
    galleryId: "__ext_dir_taka_ishii_tokyo",
    name: "Taka Ishii Gallery",
    country: "일본",
    city: "Tokyo",
    website: "https://www.takaishiigallery.com",
    bio: "Contemporary art and photography program in Tokyo.",
    sourcePortal: "Yahoo Japan",
    sourceUrl: "https://www.takaishiigallery.com",
  },
  {
    galleryId: "__ext_dir_tomio_tokyo",
    name: "Tomio Koyama Gallery",
    country: "일본",
    city: "Tokyo",
    website: "https://www.tomiokoyamagallery.com",
    bio: "Tokyo-based contemporary gallery with global roster.",
    sourcePortal: "Yahoo Japan",
    sourceUrl: "https://www.tomiokoyamagallery.com",
  },

  // UK
  {
    galleryId: "__ext_dir_lisson_london",
    name: "Lisson Gallery",
    country: "영국",
    city: "London",
    website: "https://www.lissongallery.com",
    bio: "International contemporary gallery founded in London.",
    sourcePortal: "Google",
    sourceUrl: "https://www.lissongallery.com",
  },
  {
    galleryId: "__ext_dir_whitecube_london",
    name: "White Cube",
    country: "영국",
    city: "London",
    website: "https://www.whitecube.com",
    bio: "Major gallery for contemporary art in London.",
    sourcePortal: "Google",
    sourceUrl: "https://www.whitecube.com",
  },

  // France
  {
    galleryId: "__ext_dir_perrotin_paris",
    name: "Perrotin",
    country: "프랑스",
    city: "Paris",
    website: "https://www.perrotin.com",
    bio: "Global gallery with strong program in Paris.",
    sourcePortal: "Google",
    sourceUrl: "https://www.perrotin.com",
  },
  {
    galleryId: "__ext_dir_kamel_mennour_paris",
    name: "Kamel Mennour",
    country: "프랑스",
    city: "Paris",
    website: "https://www.kamelmennour.com",
    bio: "Prominent Paris gallery with international artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.kamelmennour.com",
  },

  // USA
  {
    galleryId: "__ext_dir_gagosian_ny",
    name: "Gagosian",
    country: "미국",
    city: "New York",
    website: "https://gagosian.com",
    bio: "Large global gallery network.",
    sourcePortal: "Google",
    sourceUrl: "https://gagosian.com",
  },
  {
    galleryId: "__ext_dir_davidzwirner_ny",
    name: "David Zwirner",
    country: "미국",
    city: "New York",
    website: "https://www.davidzwirner.com",
    bio: "Influential contemporary gallery in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.davidzwirner.com",
  },
  {
    galleryId: "__ext_dir_blumpoe_la",
    name: "Blum & Poe",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.blumandpoe.com",
    bio: "Contemporary gallery in Los Angeles.",
    sourcePortal: "Google",
    sourceUrl: "https://www.blumandpoe.com",
  },
  {
    galleryId: "__ext_dir_hauserwirth_ny",
    name: "Hauser & Wirth",
    country: "미국",
    city: "New York",
    website: "https://www.hauserwirth.com",
    bio: "Global contemporary gallery with major New York presence.",
    sourcePortal: "Google",
    sourceUrl: "https://www.hauserwirth.com",
  },
  {
    galleryId: "__ext_dir_pace_ny",
    name: "Pace Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.pacegallery.com",
    bio: "Major international gallery with strong New York program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.pacegallery.com",
  },
  {
    galleryId: "__ext_dir_mariangoodman_ny",
    name: "Marian Goodman Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.mariangoodman.com",
    bio: "Influential contemporary gallery representing international artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.mariangoodman.com",
  },
  {
    galleryId: "__ext_dir_gladstone_ny",
    name: "Gladstone Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.gladstonegallery.com",
    bio: "Contemporary gallery with New York and international program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.gladstonegallery.com",
  },
  {
    galleryId: "__ext_dir_luhringaugustine_ny",
    name: "Luhring Augustine",
    country: "미국",
    city: "New York",
    website: "https://www.luhringaugustine.com",
    bio: "Chelsea gallery representing leading contemporary artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.luhringaugustine.com",
  },
  {
    galleryId: "__ext_dir_perrotin_ny",
    name: "Perrotin New York",
    country: "미국",
    city: "New York",
    website: "https://www.perrotin.com",
    bio: "New York space of Perrotin's global contemporary program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.perrotin.com",
  },
  {
    galleryId: "__ext_dir_skarnstedt_ny",
    name: "Skarstedt",
    country: "미국",
    city: "New York",
    website: "https://www.skarstedt.com",
    bio: "Modern and contemporary gallery with New York base.",
    sourcePortal: "Google",
    sourceUrl: "https://www.skarstedt.com",
  },
  {
    galleryId: "__ext_dir_jackshainman_ny",
    name: "Jack Shainman Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.jackshainman.com",
    bio: "Gallery supporting globally recognized contemporary artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.jackshainman.com",
  },
  {
    galleryId: "__ext_dir_karma_ny",
    name: "Karma",
    country: "미국",
    city: "New York",
    website: "https://www.karma.art",
    bio: "Contemporary gallery and publishing program in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.karma.art",
  },
  {
    galleryId: "__ext_dir_petzel_ny",
    name: "Petzel",
    country: "미국",
    city: "New York",
    website: "https://www.petzel.com",
    bio: "Contemporary gallery in New York representing global artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.petzel.com",
  },
  {
    galleryId: "__ext_dir_regenprojects_la",
    name: "Regen Projects",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.regenprojects.com",
    bio: "Leading Los Angeles contemporary gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.regenprojects.com",
  },
  {
    galleryId: "__ext_dir_davidkordansky_la",
    name: "David Kordansky Gallery",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.davidkordanskygallery.com",
    bio: "Major Los Angeles gallery with contemporary international roster.",
    sourcePortal: "Google",
    sourceUrl: "https://www.davidkordanskygallery.com",
  },
  {
    galleryId: "__ext_dir_hauserwirth_la",
    name: "Hauser & Wirth Los Angeles",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.hauserwirth.com",
    bio: "Los Angeles campus of global contemporary gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.hauserwirth.com",
  },
  {
    galleryId: "__ext_dir_kayonada_la",
    name: "Kohn Gallery",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.kohngallery.com",
    bio: "Contemporary art gallery in Hollywood, Los Angeles.",
    sourcePortal: "Google",
    sourceUrl: "https://www.kohngallery.com",
  },
  {
    galleryId: "__ext_dir_nightgallery_la",
    name: "Night Gallery",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.nightgallery.ca",
    bio: "Los Angeles gallery focused on contemporary emerging and mid-career artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.nightgallery.ca",
  },
  {
    galleryId: "__ext_dir_jessecheim_sf",
    name: "Jessica Silverman",
    country: "미국",
    city: "San Francisco",
    website: "https://jessicasilvermangallery.com",
    bio: "San Francisco contemporary gallery with international program.",
    sourcePortal: "Google",
    sourceUrl: "https://jessicasilvermangallery.com",
  },
  {
    galleryId: "__ext_dir_fraenkel_sf",
    name: "Fraenkel Gallery",
    country: "미국",
    city: "San Francisco",
    website: "https://fraenkelgallery.com",
    bio: "Renowned photography and contemporary art gallery in San Francisco.",
    sourcePortal: "Google",
    sourceUrl: "https://fraenkelgallery.com",
  },
  {
    galleryId: "__ext_dir_altman_siegel_sf",
    name: "Altman Siegel",
    country: "미국",
    city: "San Francisco",
    website: "https://www.altmansiegel.com",
    bio: "Contemporary gallery in San Francisco.",
    sourcePortal: "Google",
    sourceUrl: "https://www.altmansiegel.com",
  },
  {
    galleryId: "__ext_dir_rhona_hoffman_chi",
    name: "Rhona Hoffman Gallery",
    country: "미국",
    city: "Chicago",
    website: "https://www.rhonahoffmangallery.com",
    bio: "Longstanding contemporary gallery in Chicago.",
    sourcePortal: "Google",
    sourceUrl: "https://www.rhonahoffmangallery.com",
  },
  {
    galleryId: "__ext_dir_moniquemeloche_chi",
    name: "moniquemeloche",
    country: "미국",
    city: "Chicago",
    website: "https://www.moniquemeloche.com",
    bio: "Chicago gallery with contemporary global artist program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.moniquemeloche.com",
  },
  {
    galleryId: "__ext_dir_kavi_gupta_chi",
    name: "Kavi Gupta",
    country: "미국",
    city: "Chicago",
    website: "https://kavigupta.com",
    bio: "Contemporary gallery and project platform in Chicago.",
    sourcePortal: "Google",
    sourceUrl: "https://kavigupta.com",
  },
  {
    galleryId: "__ext_dir_debora_colton_hou",
    name: "Deborah Colton Gallery",
    country: "미국",
    city: "Houston",
    website: "https://www.deborahcoltongallery.com",
    bio: "Contemporary gallery in Houston, Texas.",
    sourcePortal: "Google",
    sourceUrl: "https://www.deborahcoltongallery.com",
  },
  {
    galleryId: "__ext_dir_reyesfinn_hou",
    name: "Reyes | Finn",
    country: "미국",
    city: "Houston",
    website: "https://www.reyesfinn.com",
    bio: "Houston-based contemporary art gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.reyesfinn.com",
  },
  {
    galleryId: "__ext_dir_luisdejesus_la",
    name: "Luis De Jesus Los Angeles",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.ldjal.com",
    bio: "Los Angeles gallery supporting contemporary artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.ldjal.com",
  },
  {
    galleryId: "__ext_dir_sean_kelly_ny",
    name: "Sean Kelly",
    country: "미국",
    city: "New York",
    website: "https://www.skny.com",
    bio: "Contemporary gallery in New York with international roster.",
    sourcePortal: "Google",
    sourceUrl: "https://www.skny.com",
  },
  {
    galleryId: "__ext_dir_team_ny",
    name: "Team Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.teamgal.com",
    bio: "Contemporary art gallery in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.teamgal.com",
  },
  {
    galleryId: "__ext_dir_jamesfuentes_ny",
    name: "James Fuentes",
    country: "미국",
    city: "New York",
    website: "https://jamesfuentes.com",
    bio: "Lower East Side gallery for contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://jamesfuentes.com",
  },
  {
    galleryId: "__ext_dir_sikkemajenkins_ny",
    name: "Sikkema Malloy Jenkins",
    country: "미국",
    city: "New York",
    website: "https://www.sikkemajenkinsco.com",
    bio: "Contemporary gallery in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.sikkemajenkinsco.com",
  },
  {
    galleryId: "__ext_dir_moody_ny",
    name: "Moody Gallery",
    country: "미국",
    city: "Houston",
    website: "https://www.moodygallery.com",
    bio: "Established contemporary gallery program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.moodygallery.com",
  },
  {
    galleryId: "__ext_dir_berggruen_sf",
    name: "Berggruen Gallery",
    country: "미국",
    city: "San Francisco",
    website: "https://www.berggruen.com",
    bio: "Historic San Francisco gallery focused on modern and contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://www.berggruen.com",
  },
  {
    galleryId: "__ext_dir_millsf",
    name: "Mills Morán",
    country: "미국",
    city: "San Francisco",
    website: "https://www.millsmoran.com",
    bio: "San Francisco contemporary gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.millsmoran.com",
  },
  {
    galleryId: "__ext_dir_piermarq_sea",
    name: "Pioneer Square Contemporary",
    country: "미국",
    city: "Seattle",
    website: "https://www.pioneersquare.org",
    bio: "Seattle contemporary gallery district reference source.",
    sourcePortal: "Google",
    sourceUrl: "https://www.pioneersquare.org",
  },
  {
    galleryId: "__ext_dir_marian_iba_mia",
    name: "Mindy Solomon Gallery",
    country: "미국",
    city: "Miami",
    website: "https://www.mindysolomon.com",
    bio: "Contemporary gallery with strong South Florida program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.mindysolomon.com",
  },
  {
    galleryId: "__ext_dir_ninajohnson_mia",
    name: "Nina Johnson",
    country: "미국",
    city: "Miami",
    website: "https://www.njn.la",
    bio: "Miami gallery with contemporary and cross-disciplinary program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.njn.la",
  },
  {
    galleryId: "__ext_dir_42dallas_dal",
    name: "Cris Worley Fine Arts",
    country: "미국",
    city: "Dallas",
    website: "https://www.crisworley.com",
    bio: "Dallas contemporary art gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.crisworley.com",
  },
  {
    galleryId: "__ext_dir_anat_ebgi_la",
    name: "Anat Ebgi",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.anatebgi.com",
    bio: "Los Angeles gallery representing emerging and mid-career artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.anatebgi.com",
  },
  {
    galleryId: "__ext_dir_lehmannmaupin_ny",
    name: "Lehmann Maupin",
    country: "미국",
    city: "New York",
    website: "https://www.lehmannmaupin.com",
    bio: "Contemporary gallery with a major New York program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.lehmannmaupin.com",
  },
  {
    galleryId: "__ext_dir_303_ny",
    name: "303 Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.303gallery.com",
    bio: "Longstanding contemporary art gallery in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.303gallery.com",
  },
  {
    galleryId: "__ext_dir_antonkern_ny",
    name: "Anton Kern Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.antonkerngallery.com",
    bio: "New York gallery focused on contemporary artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.antonkerngallery.com",
  },
  {
    galleryId: "__ext_dir_andrewkreps_ny",
    name: "Andrew Kreps Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.andrewkreps.com",
    bio: "Contemporary art gallery in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.andrewkreps.com",
  },
  {
    galleryId: "__ext_dir_caseykaplan_ny",
    name: "Casey Kaplan",
    country: "미국",
    city: "New York",
    website: "https://caseykaplangallery.com",
    bio: "Chelsea-based contemporary art gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://caseykaplangallery.com",
  },
  {
    galleryId: "__ext_dir_tinakim_ny",
    name: "Tina Kim Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.tinakimgallery.com",
    bio: "Contemporary gallery with transnational artist program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.tinakimgallery.com",
  },
  {
    galleryId: "__ext_dir_jamescohan_ny",
    name: "James Cohan",
    country: "미국",
    city: "New York",
    website: "https://www.jamescohan.com",
    bio: "Contemporary gallery with New York flagship spaces.",
    sourcePortal: "Google",
    sourceUrl: "https://www.jamescohan.com",
  },
  {
    galleryId: "__ext_dir_kasmin_ny",
    name: "Kasmin",
    country: "미국",
    city: "New York",
    website: "https://www.kasmingallery.com",
    bio: "New York gallery for modern and contemporary artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.kasmingallery.com",
  },
  {
    galleryId: "__ext_dir_ppow_ny",
    name: "PPOW",
    country: "미국",
    city: "New York",
    website: "https://www.ppowgallery.com",
    bio: "Established contemporary gallery in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.ppowgallery.com",
  },
  {
    galleryId: "__ext_dir_milesmcenery_ny",
    name: "Miles McEnery Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.milesmcenery.com",
    bio: "Contemporary art gallery with multiple New York spaces.",
    sourcePortal: "Google",
    sourceUrl: "https://www.milesmcenery.com",
  },
  {
    galleryId: "__ext_dir_matthewmarks_ny",
    name: "Matthew Marks Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.matthewmarks.com",
    bio: "Major contemporary gallery with long-running New York program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.matthewmarks.com",
  },
  {
    galleryId: "__ext_dir_paulacooper_ny",
    name: "Paula Cooper Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.paulacoopergallery.com",
    bio: "Influential contemporary gallery in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.paulacoopergallery.com",
  },
  {
    galleryId: "__ext_dir_marianneboesky_ny",
    name: "Marianne Boesky Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.marianneboeskygallery.com",
    bio: "Contemporary art gallery with Chelsea and Upper East Side spaces.",
    sourcePortal: "Google",
    sourceUrl: "https://www.marianneboeskygallery.com",
  },
  {
    galleryId: "__ext_dir_dcmoore_ny",
    name: "DC Moore Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.dcmooregallery.com",
    bio: "New York gallery for modern and contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://www.dcmooregallery.com",
  },
  {
    galleryId: "__ext_dir_bortolami_ny",
    name: "Bortolami",
    country: "미국",
    city: "New York",
    website: "https://www.bortolamigallery.com",
    bio: "Contemporary gallery in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.bortolamigallery.com",
  },
  {
    galleryId: "__ext_dir_canada_ny",
    name: "Canada",
    country: "미국",
    city: "New York",
    website: "https://www.canadanewyork.com",
    bio: "Contemporary gallery in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.canadanewyork.com",
  },
  {
    galleryId: "__ext_dir_thehole_ny",
    name: "The Hole",
    country: "미국",
    city: "New York",
    website: "https://www.thehole.com",
    bio: "Contemporary gallery with New York program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.thehole.com",
  },
  {
    galleryId: "__ext_dir_deitch_la",
    name: "Jeffrey Deitch",
    country: "미국",
    city: "Los Angeles",
    website: "https://deitch.com",
    bio: "Contemporary gallery and curatorial program in Los Angeles.",
    sourcePortal: "Google",
    sourceUrl: "https://deitch.com",
  },
  {
    galleryId: "__ext_dir_vsf_la",
    name: "Various Small Fires",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.vsf.la",
    bio: "Los Angeles gallery for emerging and mid-career artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.vsf.la",
  },
  {
    galleryId: "__ext_dir_ghebaly_la",
    name: "Francois Ghebaly",
    country: "미국",
    city: "Los Angeles",
    website: "https://ghebaly.com",
    bio: "Contemporary gallery with strong Los Angeles program.",
    sourcePortal: "Google",
    sourceUrl: "https://ghebaly.com",
  },
  {
    galleryId: "__ext_dir_vielmetter_la",
    name: "Vielmetter Los Angeles",
    country: "미국",
    city: "Los Angeles",
    website: "https://vielmetter.com",
    bio: "Contemporary gallery in Los Angeles.",
    sourcePortal: "Google",
    sourceUrl: "https://vielmetter.com",
  },
  {
    galleryId: "__ext_dir_commonwealth_la",
    name: "Commonwealth and Council",
    country: "미국",
    city: "Los Angeles",
    website: "https://commonwealthandcouncil.com",
    bio: "Los Angeles contemporary art gallery and project space.",
    sourcePortal: "Google",
    sourceUrl: "https://commonwealthandcouncil.com",
  },
  {
    galleryId: "__ext_dir_parker_la",
    name: "Parker Gallery",
    country: "미국",
    city: "Los Angeles",
    website: "https://parkergallery.com",
    bio: "Contemporary and historical exhibitions in Los Angeles.",
    sourcePortal: "Google",
    sourceUrl: "https://parkergallery.com",
  },
  {
    galleryId: "__ext_dir_chateaushatto_la",
    name: "Chateau Shatto",
    country: "미국",
    city: "Los Angeles",
    website: "https://chateaushatto.com",
    bio: "Contemporary gallery in Los Angeles.",
    sourcePortal: "Google",
    sourceUrl: "https://chateaushatto.com",
  },
  {
    galleryId: "__ext_dir_moranmoran_la",
    name: "Moran Moran",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.moranmoran.com",
    bio: "Los Angeles gallery for contemporary artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.moranmoran.com",
  },
  {
    galleryId: "__ext_dir_steveturner_la",
    name: "Steve Turner",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.steveturner.la",
    bio: "Contemporary gallery in Los Angeles.",
    sourcePortal: "Google",
    sourceUrl: "https://www.steveturner.la",
  },
  {
    galleryId: "__ext_dir_ochi_la",
    name: "OCHI",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.ochigallery.com",
    bio: "Contemporary gallery in Los Angeles.",
    sourcePortal: "Google",
    sourceUrl: "https://www.ochigallery.com",
  },
  {
    galleryId: "__ext_dir_belami_la",
    name: "Bel Ami",
    country: "미국",
    city: "Los Angeles",
    website: "https://belami.info",
    bio: "Contemporary gallery in Los Angeles.",
    sourcePortal: "Google",
    sourceUrl: "https://belami.info",
  },
  {
    galleryId: "__ext_dir_renabransten_sf",
    name: "Rena Bransten Gallery",
    country: "미국",
    city: "San Francisco",
    website: "https://renabranstengallery.com",
    bio: "Contemporary gallery in San Francisco.",
    sourcePortal: "Google",
    sourceUrl: "https://renabranstengallery.com",
  },
  {
    galleryId: "__ext_dir_hosfelt_sf",
    name: "Hosfelt Gallery",
    country: "미국",
    city: "San Francisco",
    website: "https://hosfeltgallery.com",
    bio: "San Francisco contemporary gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://hosfeltgallery.com",
  },
  {
    galleryId: "__ext_dir_cclark_sf",
    name: "Catharine Clark Gallery",
    country: "미국",
    city: "San Francisco",
    website: "https://www.cclarkgallery.com",
    bio: "Contemporary gallery in San Francisco.",
    sourcePortal: "Google",
    sourceUrl: "https://www.cclarkgallery.com",
  },
  {
    galleryId: "__ext_dir_haines_sf",
    name: "Haines Gallery",
    country: "미국",
    city: "San Francisco",
    website: "https://hainesgallery.com",
    bio: "San Francisco gallery focused on contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://hainesgallery.com",
  },
  {
    galleryId: "__ext_dir_anthonymeier_sf",
    name: "Anthony Meier",
    country: "미국",
    city: "San Francisco",
    website: "https://anthonymeier.com",
    bio: "Contemporary art gallery in San Francisco.",
    sourcePortal: "Google",
    sourceUrl: "https://anthonymeier.com",
  },
  {
    galleryId: "__ext_dir_corbett_chi",
    name: "Corbett vs. Dempsey",
    country: "미국",
    city: "Chicago",
    website: "https://corbettvsdempsey.com",
    bio: "Chicago gallery for modern and contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://corbettvsdempsey.com",
  },
  {
    galleryId: "__ext_dir_richardgray_chi",
    name: "Richard Gray Gallery",
    country: "미국",
    city: "Chicago",
    website: "https://www.richardgraygallery.com",
    bio: "Established modern and contemporary gallery in Chicago.",
    sourcePortal: "Google",
    sourceUrl: "https://www.richardgraygallery.com",
  },
  {
    galleryId: "__ext_dir_gray_chi",
    name: "GRAY",
    country: "미국",
    city: "Chicago",
    website: "https://www.graygallery.com",
    bio: "Contemporary and modern art gallery in Chicago.",
    sourcePortal: "Google",
    sourceUrl: "https://www.graygallery.com",
  },
  {
    galleryId: "__ext_dir_patron_chi",
    name: "Patron",
    country: "미국",
    city: "Chicago",
    website: "https://www.patrongallery.com",
    bio: "Contemporary gallery in Chicago.",
    sourcePortal: "Google",
    sourceUrl: "https://www.patrongallery.com",
  },
  {
    galleryId: "__ext_dir_marianeibrahim_chi",
    name: "Mariane Ibrahim",
    country: "미국",
    city: "Chicago",
    website: "https://www.marianeibrahim.com",
    bio: "Chicago-based contemporary gallery with international program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.marianeibrahim.com",
  },
  {
    galleryId: "__ext_dir_mcclain_hou",
    name: "McClain Gallery",
    country: "미국",
    city: "Houston",
    website: "https://www.mcclaingallery.com",
    bio: "Contemporary and modern art gallery in Houston.",
    sourcePortal: "Google",
    sourceUrl: "https://www.mcclaingallery.com",
  },
  {
    galleryId: "__ext_dir_inman_hou",
    name: "Inman Gallery",
    country: "미국",
    city: "Houston",
    website: "https://www.inmangallery.com",
    bio: "Houston contemporary art gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.inmangallery.com",
  },
  {
    galleryId: "__ext_dir_barbaradavis_hou",
    name: "Barbara Davis Gallery",
    country: "미국",
    city: "Houston",
    website: "https://www.barbaradavisgallery.com",
    bio: "Contemporary art gallery in Houston.",
    sourcePortal: "Google",
    sourceUrl: "https://www.barbaradavisgallery.com",
  },
  {
    galleryId: "__ext_dir_sicardi_hou",
    name: "Sicardi | Ayers | Bacino",
    country: "미국",
    city: "Houston",
    website: "https://www.sicardi.com",
    bio: "Houston gallery with contemporary Latin American art focus.",
    sourcePortal: "Google",
    sourceUrl: "https://www.sicardi.com",
  },
  {
    galleryId: "__ext_dir_fredricsnitzer_mia",
    name: "Fredric Snitzer Gallery",
    country: "미국",
    city: "Miami",
    website: "https://www.fredricsnitzergallery.com",
    bio: "Contemporary gallery in Miami.",
    sourcePortal: "Google",
    sourceUrl: "https://www.fredricsnitzergallery.com",
  },
  {
    galleryId: "__ext_dir_emersondorsch_mia",
    name: "Emerson Dorsch",
    country: "미국",
    city: "Miami",
    website: "https://www.emersondorsch.com",
    bio: "Contemporary gallery and project space in Miami.",
    sourcePortal: "Google",
    sourceUrl: "https://www.emersondorsch.com",
  },
  {
    galleryId: "__ext_dir_spinello_mia",
    name: "Spinello Projects",
    country: "미국",
    city: "Miami",
    website: "https://www.spinelloprojects.com",
    bio: "Miami contemporary art gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.spinelloprojects.com",
  },
  {
    galleryId: "__ext_dir_davidcastillo_mia",
    name: "David Castillo",
    country: "미국",
    city: "Miami",
    website: "https://www.davidcastillogallery.com",
    bio: "Contemporary gallery in Miami.",
    sourcePortal: "Google",
    sourceUrl: "https://www.davidcastillogallery.com",
  },
  {
    galleryId: "__ext_dir_barrywhistler_dal",
    name: "Barry Whistler Gallery",
    country: "미국",
    city: "Dallas",
    website: "https://www.barrywhistlergallery.com",
    bio: "Contemporary gallery in Dallas.",
    sourcePortal: "Google",
    sourceUrl: "https://www.barrywhistlergallery.com",
  },
  {
    galleryId: "__ext_dir_erincluley_dal",
    name: "Erin Cluley Gallery",
    country: "미국",
    city: "Dallas",
    website: "https://www.erincluleygallery.com",
    bio: "Dallas contemporary gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.erincluleygallery.com",
  },
  {
    galleryId: "__ext_dir_urbane_dal",
    name: "Galleri Urbane",
    country: "미국",
    city: "Dallas",
    website: "https://www.galleriurbane.com",
    bio: "Contemporary gallery in Dallas.",
    sourcePortal: "Google",
    sourceUrl: "https://www.galleriurbane.com",
  },
  {
    galleryId: "__ext_dir_conduit_dal",
    name: "Conduit Gallery",
    country: "미국",
    city: "Dallas",
    website: "https://www.conduitgallery.com",
    bio: "Contemporary gallery in Dallas.",
    sourcePortal: "Google",
    sourceUrl: "https://www.conduitgallery.com",
  },
  {
    galleryId: "__ext_dir_keijserskoning_dal",
    name: "Keijsers Koning",
    country: "미국",
    city: "Dallas",
    website: "https://www.keijserskoning.com",
    bio: "Dallas gallery focused on contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://www.keijserskoning.com",
  },
  {
    galleryId: "__ext_dir_gregkucera_sea",
    name: "Greg Kucera Gallery",
    country: "미국",
    city: "Seattle",
    website: "https://www.gregkucera.com",
    bio: "Seattle contemporary art gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.gregkucera.com",
  },
  {
    galleryId: "__ext_dir_jamesharris_sea",
    name: "James Harris Gallery",
    country: "미국",
    city: "Seattle",
    website: "https://www.jamesharrisgallery.com",
    bio: "Contemporary gallery in Seattle.",
    sourcePortal: "Google",
    sourceUrl: "https://www.jamesharrisgallery.com",
  },
  {
    galleryId: "__ext_dir_jrinehart_sea",
    name: "J. Rinehart Gallery",
    country: "미국",
    city: "Seattle",
    website: "https://www.jrinehartgallery.com",
    bio: "Seattle gallery focused on contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://www.jrinehartgallery.com",
  },
  {
    galleryId: "__ext_dir_winstonwachter_sea",
    name: "Winston Wachter Fine Art",
    country: "미국",
    city: "Seattle",
    website: "https://www.winstonwachter.com",
    bio: "Contemporary art gallery in Seattle.",
    sourcePortal: "Google",
    sourceUrl: "https://www.winstonwachter.com",
  },
  {
    galleryId: "__ext_dir_fosterwhite_sea",
    name: "Foster/White Gallery",
    country: "미국",
    city: "Seattle",
    website: "https://fosterwhite.com",
    bio: "Established gallery in Seattle.",
    sourcePortal: "Google",
    sourceUrl: "https://fosterwhite.com",
  },
  {
    galleryId: "__ext_dir_barbarakrakow_bos",
    name: "Barbara Krakow Gallery",
    country: "미국",
    city: "Boston",
    website: "https://www.barbarakrakowgallery.com",
    bio: "Contemporary gallery in Boston.",
    sourcePortal: "Google",
    sourceUrl: "https://www.barbarakrakowgallery.com",
  },
  {
    galleryId: "__ext_dir_krakowwitkin_bos",
    name: "Krakow Witkin Gallery",
    country: "미국",
    city: "Boston",
    website: "https://www.krakowwitkingallery.com",
    bio: "Boston gallery for modern and contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://www.krakowwitkingallery.com",
  },
  {
    galleryId: "__ext_dir_naga_bos",
    name: "Gallery NAGA",
    country: "미국",
    city: "Boston",
    website: "https://www.gallerynaga.com",
    bio: "Contemporary art gallery in Boston.",
    sourcePortal: "Google",
    sourceUrl: "https://www.gallerynaga.com",
  },
  {
    galleryId: "__ext_dir_fleisherollman_phi",
    name: "Fleisher/Ollman",
    country: "미국",
    city: "Philadelphia",
    website: "https://www.fleisher-ollmangallery.com",
    bio: "Philadelphia gallery with contemporary and self-taught art program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.fleisher-ollmangallery.com",
  },
  {
    galleryId: "__ext_dir_locks_phi",
    name: "Locks Gallery",
    country: "미국",
    city: "Philadelphia",
    website: "https://www.locksgallery.com",
    bio: "Contemporary art gallery in Philadelphia.",
    sourcePortal: "Google",
    sourceUrl: "https://www.locksgallery.com",
  },
  {
    galleryId: "__ext_dir_pentimenti_phi",
    name: "Pentimenti Gallery",
    country: "미국",
    city: "Philadelphia",
    website: "https://www.pentimenti.com",
    bio: "Philadelphia contemporary art gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.pentimenti.com",
  },
  {
    galleryId: "__ext_dir_bridgettemayer_phi",
    name: "Bridgette Mayer Gallery",
    country: "미국",
    city: "Philadelphia",
    website: "https://www.bridgettemayergallery.com",
    bio: "Contemporary gallery in Philadelphia.",
    sourcePortal: "Google",
    sourceUrl: "https://www.bridgettemayergallery.com",
  },
  {
    galleryId: "__ext_dir_addisonripley_dc",
    name: "Addison/Ripley Fine Art",
    country: "미국",
    city: "Washington",
    website: "https://www.addisonripleyfineart.com",
    bio: "Contemporary art gallery in Washington, DC.",
    sourcePortal: "Google",
    sourceUrl: "https://www.addisonripleyfineart.com",
  },
  {
    galleryId: "__ext_dir_connersmith_dc",
    name: "Connersmith",
    country: "미국",
    city: "Washington",
    website: "https://www.connersmith.us",
    bio: "Washington, DC gallery focused on contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://www.connersmith.us",
  },
  {
    galleryId: "__ext_dir_transformer_dc",
    name: "Transformer",
    country: "미국",
    city: "Washington",
    website: "https://www.transformerdc.org",
    bio: "Contemporary visual arts organization in Washington, DC.",
    sourcePortal: "Google",
    sourceUrl: "https://www.transformerdc.org",
  },
  {
    galleryId: "__ext_dir_hamiltonian_dc",
    name: "Hamiltonian Artists",
    country: "미국",
    city: "Washington",
    website: "https://www.hamiltonianartists.org",
    bio: "Contemporary art exhibition and fellowship platform in Washington, DC.",
    sourcePortal: "Google",
    sourceUrl: "https://www.hamiltonianartists.org",
  },
  {
    galleryId: "__ext_dir_pdxcontemporary_por",
    name: "PDX Contemporary Art",
    country: "미국",
    city: "Portland",
    website: "https://www.pdxcontemporaryart.com",
    bio: "Contemporary gallery in Portland.",
    sourcePortal: "Google",
    sourceUrl: "https://www.pdxcontemporaryart.com",
  },
  {
    galleryId: "__ext_dir_elizabethleach_por",
    name: "Elizabeth Leach Gallery",
    country: "미국",
    city: "Portland",
    website: "https://www.elizabethleach.com",
    bio: "Portland contemporary gallery with regional and international artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.elizabethleach.com",
  },
  {
    galleryId: "__ext_dir_upfor_por",
    name: "Upfor",
    country: "미국",
    city: "Portland",
    website: "https://www.upforgallery.com",
    bio: "Contemporary art gallery in Portland.",
    sourcePortal: "Google",
    sourceUrl: "https://www.upforgallery.com",
  },
  {
    galleryId: "__ext_dir_russolee_por",
    name: "Russo Lee Gallery",
    country: "미국",
    city: "Portland",
    website: "https://www.russoleegallery.com",
    bio: "Longstanding contemporary gallery in Portland.",
    sourcePortal: "Google",
    sourceUrl: "https://www.russoleegallery.com",
  },
  {
    galleryId: "__ext_dir_jacksonfine_atl",
    name: "Jackson Fine Art",
    country: "미국",
    city: "Atlanta",
    website: "https://www.jacksonfineart.com",
    bio: "Atlanta gallery focused on photography and contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://www.jacksonfineart.com",
  },
  {
    galleryId: "__ext_dir_alanavery_atl",
    name: "Alan Avery Art Company",
    country: "미국",
    city: "Atlanta",
    website: "https://www.alanaveryartcompany.com",
    bio: "Contemporary and modern gallery in Atlanta.",
    sourcePortal: "Google",
    sourceUrl: "https://www.alanaveryartcompany.com",
  },
  {
    galleryId: "__ext_dir_marciawood_atl",
    name: "Marcia Wood Gallery",
    country: "미국",
    city: "Atlanta",
    website: "https://www.marciawoodgallery.com",
    bio: "Contemporary gallery in Atlanta.",
    sourcePortal: "Google",
    sourceUrl: "https://www.marciawoodgallery.com",
  },
  {
    galleryId: "__ext_dir_whitespace_atl",
    name: "Whitespace",
    country: "미국",
    city: "Atlanta",
    website: "https://www.whitespace814.com",
    bio: "Atlanta contemporary gallery and project space.",
    sourcePortal: "Google",
    sourceUrl: "https://www.whitespace814.com",
  },
  {
    galleryId: "__ext_dir_robischon_den",
    name: "Robischon Gallery",
    country: "미국",
    city: "Denver",
    website: "https://www.robischon.com",
    bio: "Contemporary gallery in Denver.",
    sourcePortal: "Google",
    sourceUrl: "https://www.robischon.com",
  },
  {
    galleryId: "__ext_dir_rule_den",
    name: "Rule Gallery",
    country: "미국",
    city: "Denver",
    website: "https://www.rulegallery.com",
    bio: "Contemporary gallery with Denver base.",
    sourcePortal: "Google",
    sourceUrl: "https://www.rulegallery.com",
  },
  {
    galleryId: "__ext_dir_kcontemporary_den",
    name: "K Contemporary",
    country: "미국",
    city: "Denver",
    website: "https://www.kcontemporaryart.com",
    bio: "Contemporary art gallery in Denver.",
    sourcePortal: "Google",
    sourceUrl: "https://www.kcontemporaryart.com",
  },
  {
    galleryId: "__ext_dir_davidbsmith_den",
    name: "David B. Smith Gallery",
    country: "미국",
    city: "Denver",
    website: "https://www.davidbsmithgallery.com",
    bio: "Denver gallery focused on contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://www.davidbsmithgallery.com",
  },
  {
    galleryId: "__ext_dir_arthurroger_no",
    name: "Arthur Roger Gallery",
    country: "미국",
    city: "New Orleans",
    website: "https://arthurrogergallery.com",
    bio: "Contemporary gallery in New Orleans.",
    sourcePortal: "Google",
    sourceUrl: "https://arthurrogergallery.com",
  },
  {
    galleryId: "__ext_dir_jonathanferrara_no",
    name: "Jonathan Ferrara Gallery",
    country: "미국",
    city: "New Orleans",
    website: "https://www.jonathanferraragallery.com",
    bio: "Contemporary art gallery in New Orleans.",
    sourcePortal: "Google",
    sourceUrl: "https://www.jonathanferraragallery.com",
  },
  {
    galleryId: "__ext_dir_octavia_no",
    name: "Octavia Art Gallery",
    country: "미국",
    city: "New Orleans",
    website: "https://www.octaviaartgallery.com",
    bio: "Contemporary gallery in New Orleans.",
    sourcePortal: "Google",
    sourceUrl: "https://www.octaviaartgallery.com",
  },

  // Germany
  {
    galleryId: "__ext_dir_sprueth_berlin",
    name: "Sprüth Magers",
    country: "독일",
    city: "Berlin",
    website: "https://www.spruethmagers.com",
    bio: "Leading contemporary gallery with Berlin base.",
    sourcePortal: "Google",
    sourceUrl: "https://www.spruethmagers.com",
  },
  {
    galleryId: "__ext_dir_koenig_berlin",
    name: "König Galerie",
    country: "독일",
    city: "Berlin",
    website: "https://www.koeniggalerie.com",
    bio: "Contemporary gallery in Berlin.",
    sourcePortal: "Google",
    sourceUrl: "https://www.koeniggalerie.com",
  },

  // Italy
  {
    galleryId: "__ext_dir_massimo_milan",
    name: "Massimo De Carlo",
    country: "이탈리아",
    city: "Milan",
    website: "https://www.massimodecarlo.com",
    bio: "Major contemporary gallery in Milan.",
    sourcePortal: "Google",
    sourceUrl: "https://www.massimodecarlo.com",
  },
  {
    galleryId: "__ext_dir_continua_sg",
    name: "Galleria Continua",
    country: "이탈리아",
    city: "San Gimignano",
    website: "https://www.galleriacontinua.com",
    bio: "International gallery network founded in Italy.",
    sourcePortal: "Google",
    sourceUrl: "https://www.galleriacontinua.com",
  },

  // China
  {
    galleryId: "__ext_dir_shanghart_shanghai",
    name: "ShanghART Gallery",
    country: "중국",
    city: "Shanghai",
    website: "https://www.shanghartgallery.com",
    bio: "One of the earliest contemporary galleries in China.",
    sourcePortal: "Baidu",
    sourceUrl: "https://www.shanghartgallery.com",
  },
  {
    galleryId: "__ext_dir_longmarch_beijing",
    name: "Long March Space",
    country: "중국",
    city: "Beijing",
    website: "https://www.longmarchspace.com",
    bio: "Contemporary gallery and project space in Beijing.",
    sourcePortal: "Baidu",
    sourceUrl: "https://www.longmarchspace.com",
  },

  // Switzerland
  {
    galleryId: "__ext_dir_presenhuber_zurich",
    name: "Galerie Eva Presenhuber",
    country: "스위스",
    city: "Zurich",
    website: "https://www.presenhuber.com",
    bio: "Leading Swiss gallery in Zurich.",
    sourcePortal: "Google",
    sourceUrl: "https://www.presenhuber.com",
  },

  // Australia
  {
    galleryId: "__ext_dir_roslyn_sydney",
    name: "Roslyn Oxley9 Gallery",
    country: "호주",
    city: "Sydney",
    website: "https://www.roslynoxley9.com.au",
    bio: "Prominent Sydney contemporary gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.roslynoxley9.com.au",
  },
  {
    galleryId: "__ext_dir_anna_melbourne",
    name: "Anna Schwartz Gallery",
    country: "호주",
    city: "Melbourne",
    website: "https://www.annaschwartzgallery.com",
    bio: "Contemporary gallery in Melbourne.",
    sourcePortal: "Google",
    sourceUrl: "https://www.annaschwartzgallery.com",
  },
];

