export type PortalGallerySeed = {
  galleryId: string;
  name: string;
  country: string;
  city: string;
  website?: string;
  bio?: string;
  sourcePortal: string;
  sourceUrl?: string;
  externalEmail?: string;
};

// Initial directory seeds from major-portal style discovery.
// This list is intentionally explicit and easy to extend per country/city.
export const PORTAL_GALLERY_SEEDS: PortalGallerySeed[] = [
  // Korea
  {
    galleryId: "__ext_dir_kukje_seoul",
    name: "Kukje Gallery",
    country: "한국",
    city: "Seoul",
    website: "https://www.kukjegallery.com",
    bio: "Leading contemporary gallery in Seoul.",
    sourcePortal: "Naver",
    sourceUrl: "https://www.kukjegallery.com",
  },
  {
    galleryId: "__ext_dir_hyundai_seoul",
    name: "Gallery Hyundai",
    country: "한국",
    city: "Seoul",
    website: "https://www.galleryhyundai.com",
    bio: "Historic Korean gallery with international program.",
    sourcePortal: "Naver",
    sourceUrl: "https://www.galleryhyundai.com",
  },
  {
    galleryId: "__ext_dir_johyun_busan",
    name: "Johyun Gallery",
    country: "한국",
    city: "Busan",
    website: "https://www.johyungallery.com",
    bio: "Major gallery in Busan for Korean and global artists.",
    sourcePortal: "Naver",
    sourceUrl: "https://www.johyungallery.com",
  },

  // Japan
  {
    galleryId: "__ext_dir_taka_ishii_tokyo",
    name: "Taka Ishii Gallery",
    country: "일본",
    city: "Tokyo",
    website: "https://www.takaishiigallery.com",
    bio: "Contemporary art and photography program in Tokyo.",
    sourcePortal: "Yahoo Japan",
    sourceUrl: "https://www.takaishiigallery.com",
  },
  {
    galleryId: "__ext_dir_tomio_tokyo",
    name: "Tomio Koyama Gallery",
    country: "일본",
    city: "Tokyo",
    website: "https://www.tomiokoyamagallery.com",
    bio: "Tokyo-based contemporary gallery with global roster.",
    sourcePortal: "Yahoo Japan",
    sourceUrl: "https://www.tomiokoyamagallery.com",
  },

  // UK
  {
    galleryId: "__ext_dir_lisson_london",
    name: "Lisson Gallery",
    country: "영국",
    city: "London",
    website: "https://www.lissongallery.com",
    bio: "International contemporary gallery founded in London.",
    sourcePortal: "Google",
    sourceUrl: "https://www.lissongallery.com",
  },
  {
    galleryId: "__ext_dir_whitecube_london",
    name: "White Cube",
    country: "영국",
    city: "London",
    website: "https://www.whitecube.com",
    bio: "Major gallery for contemporary art in London.",
    sourcePortal: "Google",
    sourceUrl: "https://www.whitecube.com",
  },

  // France
  {
    galleryId: "__ext_dir_perrotin_paris",
    name: "Perrotin",
    country: "프랑스",
    city: "Paris",
    website: "https://www.perrotin.com",
    bio: "Global gallery with strong program in Paris.",
    sourcePortal: "Google",
    sourceUrl: "https://www.perrotin.com",
  },
  {
    galleryId: "__ext_dir_kamel_mennour_paris",
    name: "Kamel Mennour",
    country: "프랑스",
    city: "Paris",
    website: "https://www.kamelmennour.com",
    bio: "Prominent Paris gallery with international artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.kamelmennour.com",
  },

  // USA
  {
    galleryId: "__ext_dir_gagosian_ny",
    name: "Gagosian",
    country: "미국",
    city: "New York",
    website: "https://gagosian.com",
    bio: "Large global gallery network.",
    sourcePortal: "Google",
    sourceUrl: "https://gagosian.com",
  },
  {
    galleryId: "__ext_dir_davidzwirner_ny",
    name: "David Zwirner",
    country: "미국",
    city: "New York",
    website: "https://www.davidzwirner.com",
    bio: "Influential contemporary gallery in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.davidzwirner.com",
  },
  {
    galleryId: "__ext_dir_blumpoe_la",
    name: "Blum & Poe",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.blumandpoe.com",
    bio: "Contemporary gallery in Los Angeles.",
    sourcePortal: "Google",
    sourceUrl: "https://www.blumandpoe.com",
  },
  {
    galleryId: "__ext_dir_hauserwirth_ny",
    name: "Hauser & Wirth",
    country: "미국",
    city: "New York",
    website: "https://www.hauserwirth.com",
    bio: "Global contemporary gallery with major New York presence.",
    sourcePortal: "Google",
    sourceUrl: "https://www.hauserwirth.com",
  },
  {
    galleryId: "__ext_dir_pace_ny",
    name: "Pace Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.pacegallery.com",
    bio: "Major international gallery with strong New York program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.pacegallery.com",
  },
  {
    galleryId: "__ext_dir_mariangoodman_ny",
    name: "Marian Goodman Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.mariangoodman.com",
    bio: "Influential contemporary gallery representing international artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.mariangoodman.com",
  },
  {
    galleryId: "__ext_dir_gladstone_ny",
    name: "Gladstone Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.gladstonegallery.com",
    bio: "Contemporary gallery with New York and international program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.gladstonegallery.com",
  },
  {
    galleryId: "__ext_dir_luhringaugustine_ny",
    name: "Luhring Augustine",
    country: "미국",
    city: "New York",
    website: "https://www.luhringaugustine.com",
    bio: "Chelsea gallery representing leading contemporary artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.luhringaugustine.com",
  },
  {
    galleryId: "__ext_dir_perrotin_ny",
    name: "Perrotin New York",
    country: "미국",
    city: "New York",
    website: "https://www.perrotin.com",
    bio: "New York space of Perrotin's global contemporary program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.perrotin.com",
  },
  {
    galleryId: "__ext_dir_skarnstedt_ny",
    name: "Skarstedt",
    country: "미국",
    city: "New York",
    website: "https://www.skarstedt.com",
    bio: "Modern and contemporary gallery with New York base.",
    sourcePortal: "Google",
    sourceUrl: "https://www.skarstedt.com",
  },
  {
    galleryId: "__ext_dir_jackshainman_ny",
    name: "Jack Shainman Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.jackshainman.com",
    bio: "Gallery supporting globally recognized contemporary artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.jackshainman.com",
  },
  {
    galleryId: "__ext_dir_karma_ny",
    name: "Karma",
    country: "미국",
    city: "New York",
    website: "https://www.karma.art",
    bio: "Contemporary gallery and publishing program in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.karma.art",
  },
  {
    galleryId: "__ext_dir_petzel_ny",
    name: "Petzel",
    country: "미국",
    city: "New York",
    website: "https://www.petzel.com",
    bio: "Contemporary gallery in New York representing global artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.petzel.com",
  },
  {
    galleryId: "__ext_dir_regenprojects_la",
    name: "Regen Projects",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.regenprojects.com",
    bio: "Leading Los Angeles contemporary gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.regenprojects.com",
  },
  {
    galleryId: "__ext_dir_davidkordansky_la",
    name: "David Kordansky Gallery",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.davidkordanskygallery.com",
    bio: "Major Los Angeles gallery with contemporary international roster.",
    sourcePortal: "Google",
    sourceUrl: "https://www.davidkordanskygallery.com",
  },
  {
    galleryId: "__ext_dir_hauserwirth_la",
    name: "Hauser & Wirth Los Angeles",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.hauserwirth.com",
    bio: "Los Angeles campus of global contemporary gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.hauserwirth.com",
  },
  {
    galleryId: "__ext_dir_kayonada_la",
    name: "Kohn Gallery",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.kohngallery.com",
    bio: "Contemporary art gallery in Hollywood, Los Angeles.",
    sourcePortal: "Google",
    sourceUrl: "https://www.kohngallery.com",
  },
  {
    galleryId: "__ext_dir_nightgallery_la",
    name: "Night Gallery",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.nightgallery.ca",
    bio: "Los Angeles gallery focused on contemporary emerging and mid-career artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.nightgallery.ca",
  },
  {
    galleryId: "__ext_dir_jessecheim_sf",
    name: "Jessica Silverman",
    country: "미국",
    city: "San Francisco",
    website: "https://jessicasilvermangallery.com",
    bio: "San Francisco contemporary gallery with international program.",
    sourcePortal: "Google",
    sourceUrl: "https://jessicasilvermangallery.com",
  },
  {
    galleryId: "__ext_dir_fraenkel_sf",
    name: "Fraenkel Gallery",
    country: "미국",
    city: "San Francisco",
    website: "https://fraenkelgallery.com",
    bio: "Renowned photography and contemporary art gallery in San Francisco.",
    sourcePortal: "Google",
    sourceUrl: "https://fraenkelgallery.com",
  },
  {
    galleryId: "__ext_dir_altman_siegel_sf",
    name: "Altman Siegel",
    country: "미국",
    city: "San Francisco",
    website: "https://www.altmansiegel.com",
    bio: "Contemporary gallery in San Francisco.",
    sourcePortal: "Google",
    sourceUrl: "https://www.altmansiegel.com",
  },
  {
    galleryId: "__ext_dir_rhona_hoffman_chi",
    name: "Rhona Hoffman Gallery",
    country: "미국",
    city: "Chicago",
    website: "https://www.rhonahoffmangallery.com",
    bio: "Longstanding contemporary gallery in Chicago.",
    sourcePortal: "Google",
    sourceUrl: "https://www.rhonahoffmangallery.com",
  },
  {
    galleryId: "__ext_dir_moniquemeloche_chi",
    name: "moniquemeloche",
    country: "미국",
    city: "Chicago",
    website: "https://www.moniquemeloche.com",
    bio: "Chicago gallery with contemporary global artist program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.moniquemeloche.com",
  },
  {
    galleryId: "__ext_dir_kavi_gupta_chi",
    name: "Kavi Gupta",
    country: "미국",
    city: "Chicago",
    website: "https://kavigupta.com",
    bio: "Contemporary gallery and project platform in Chicago.",
    sourcePortal: "Google",
    sourceUrl: "https://kavigupta.com",
  },
  {
    galleryId: "__ext_dir_debora_colton_hou",
    name: "Deborah Colton Gallery",
    country: "미국",
    city: "Houston",
    website: "https://www.deborahcoltongallery.com",
    bio: "Contemporary gallery in Houston, Texas.",
    sourcePortal: "Google",
    sourceUrl: "https://www.deborahcoltongallery.com",
  },
  {
    galleryId: "__ext_dir_reyesfinn_hou",
    name: "Reyes | Finn",
    country: "미국",
    city: "Houston",
    website: "https://www.reyesfinn.com",
    bio: "Houston-based contemporary art gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.reyesfinn.com",
  },
  {
    galleryId: "__ext_dir_luisdejesus_la",
    name: "Luis De Jesus Los Angeles",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.ldjal.com",
    bio: "Los Angeles gallery supporting contemporary artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.ldjal.com",
  },
  {
    galleryId: "__ext_dir_sean_kelly_ny",
    name: "Sean Kelly",
    country: "미국",
    city: "New York",
    website: "https://www.skny.com",
    bio: "Contemporary gallery in New York with international roster.",
    sourcePortal: "Google",
    sourceUrl: "https://www.skny.com",
  },
  {
    galleryId: "__ext_dir_team_ny",
    name: "Team Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.teamgal.com",
    bio: "Contemporary art gallery in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.teamgal.com",
  },
  {
    galleryId: "__ext_dir_jamesfuentes_ny",
    name: "James Fuentes",
    country: "미국",
    city: "New York",
    website: "https://jamesfuentes.com",
    bio: "Lower East Side gallery for contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://jamesfuentes.com",
  },
  {
    galleryId: "__ext_dir_sikkemajenkins_ny",
    name: "Sikkema Malloy Jenkins",
    country: "미국",
    city: "New York",
    website: "https://www.sikkemajenkinsco.com",
    bio: "Contemporary gallery in New York.",
    sourcePortal: "Google",
    sourceUrl: "https://www.sikkemajenkinsco.com",
  },
  {
    galleryId: "__ext_dir_moody_ny",
    name: "Moody Gallery",
    country: "미국",
    city: "New York",
    website: "https://www.moodygallery.com",
    bio: "Established contemporary gallery program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.moodygallery.com",
  },
  {
    galleryId: "__ext_dir_berggruen_sf",
    name: "Berggruen Gallery",
    country: "미국",
    city: "San Francisco",
    website: "https://www.berggruen.com",
    bio: "Historic San Francisco gallery focused on modern and contemporary art.",
    sourcePortal: "Google",
    sourceUrl: "https://www.berggruen.com",
  },
  {
    galleryId: "__ext_dir_millsf",
    name: "Mills Morán",
    country: "미국",
    city: "San Francisco",
    website: "https://www.millsmoran.com",
    bio: "San Francisco contemporary gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.millsmoran.com",
  },
  {
    galleryId: "__ext_dir_piermarq_sea",
    name: "Pioneer Square Contemporary",
    country: "미국",
    city: "Seattle",
    website: "https://www.pioneersquare.org",
    bio: "Seattle contemporary gallery district reference source.",
    sourcePortal: "Google",
    sourceUrl: "https://www.pioneersquare.org",
  },
  {
    galleryId: "__ext_dir_marian_iba_mia",
    name: "Mindy Solomon Gallery",
    country: "미국",
    city: "Miami",
    website: "https://www.mindysolomon.com",
    bio: "Contemporary gallery with strong South Florida program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.mindysolomon.com",
  },
  {
    galleryId: "__ext_dir_ninajohnson_mia",
    name: "Nina Johnson",
    country: "미국",
    city: "Miami",
    website: "https://www.njn.la",
    bio: "Miami gallery with contemporary and cross-disciplinary program.",
    sourcePortal: "Google",
    sourceUrl: "https://www.njn.la",
  },
  {
    galleryId: "__ext_dir_42dallas_dal",
    name: "Cris Worley Fine Arts",
    country: "미국",
    city: "Dallas",
    website: "https://www.crisworley.com",
    bio: "Dallas contemporary art gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.crisworley.com",
  },
  {
    galleryId: "__ext_dir_anat_ebgi_la",
    name: "Anat Ebgi",
    country: "미국",
    city: "Los Angeles",
    website: "https://www.anatebgi.com",
    bio: "Los Angeles gallery representing emerging and mid-career artists.",
    sourcePortal: "Google",
    sourceUrl: "https://www.anatebgi.com",
  },

  // Germany
  {
    galleryId: "__ext_dir_sprueth_berlin",
    name: "Sprüth Magers",
    country: "독일",
    city: "Berlin",
    website: "https://www.spruethmagers.com",
    bio: "Leading contemporary gallery with Berlin base.",
    sourcePortal: "Google",
    sourceUrl: "https://www.spruethmagers.com",
  },
  {
    galleryId: "__ext_dir_koenig_berlin",
    name: "König Galerie",
    country: "독일",
    city: "Berlin",
    website: "https://www.koeniggalerie.com",
    bio: "Contemporary gallery in Berlin.",
    sourcePortal: "Google",
    sourceUrl: "https://www.koeniggalerie.com",
  },

  // Italy
  {
    galleryId: "__ext_dir_massimo_milan",
    name: "Massimo De Carlo",
    country: "이탈리아",
    city: "Milan",
    website: "https://www.massimodecarlo.com",
    bio: "Major contemporary gallery in Milan.",
    sourcePortal: "Google",
    sourceUrl: "https://www.massimodecarlo.com",
  },
  {
    galleryId: "__ext_dir_continua_sg",
    name: "Galleria Continua",
    country: "이탈리아",
    city: "San Gimignano",
    website: "https://www.galleriacontinua.com",
    bio: "International gallery network founded in Italy.",
    sourcePortal: "Google",
    sourceUrl: "https://www.galleriacontinua.com",
  },

  // China
  {
    galleryId: "__ext_dir_shanghart_shanghai",
    name: "ShanghART Gallery",
    country: "중국",
    city: "Shanghai",
    website: "https://www.shanghartgallery.com",
    bio: "One of the earliest contemporary galleries in China.",
    sourcePortal: "Baidu",
    sourceUrl: "https://www.shanghartgallery.com",
  },
  {
    galleryId: "__ext_dir_longmarch_beijing",
    name: "Long March Space",
    country: "중국",
    city: "Beijing",
    website: "https://www.longmarchspace.com",
    bio: "Contemporary gallery and project space in Beijing.",
    sourcePortal: "Baidu",
    sourceUrl: "https://www.longmarchspace.com",
  },

  // Switzerland
  {
    galleryId: "__ext_dir_presenhuber_zurich",
    name: "Galerie Eva Presenhuber",
    country: "스위스",
    city: "Zurich",
    website: "https://www.presenhuber.com",
    bio: "Leading Swiss gallery in Zurich.",
    sourcePortal: "Google",
    sourceUrl: "https://www.presenhuber.com",
  },

  // Australia
  {
    galleryId: "__ext_dir_roslyn_sydney",
    name: "Roslyn Oxley9 Gallery",
    country: "호주",
    city: "Sydney",
    website: "https://www.roslynoxley9.com.au",
    bio: "Prominent Sydney contemporary gallery.",
    sourcePortal: "Google",
    sourceUrl: "https://www.roslynoxley9.com.au",
  },
  {
    galleryId: "__ext_dir_anna_melbourne",
    name: "Anna Schwartz Gallery",
    country: "호주",
    city: "Melbourne",
    website: "https://www.annaschwartzgallery.com",
    bio: "Contemporary gallery in Melbourne.",
    sourcePortal: "Google",
    sourceUrl: "https://www.annaschwartzgallery.com",
  },
];

